/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef CURSOR_AUTODEFS_H
#define CURSOR_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_CURSOR_NAME "Cursor"
#define S3E_EXT_CURSOR_HASH 0xf7536923

#include "s3eEdk.h"

#define CURSORGLOBALS ((CursorGlobals*)s3eEdkGlobalsGet(S3E_EXT_CURSOR_HASH))
#endif /* !CURSOR_AUTODEFS_H */
