/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "Cursor_autodefs.h"
#include "s3eEdk.h"
#include "Cursor.h"
#include "Cursor_internal.h"

//Declarations of Init and Term functions
extern s3eResult CursorInit();
extern void CursorTerminate();


void CursorRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[3];
    funcPtrs[0] = (void*)Show_Cursor;
    funcPtrs[1] = (void*)Get_Cursor;
    funcPtrs[2] = (void*)Set_Cursor;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[3] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("Cursor", funcPtrs, sizeof(funcPtrs), flags, CursorInit, CursorTerminate, sizeof(CursorGlobals));
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int CursorStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&CursorRegisterExt;
    return 0;
}

int g_CursorVal = CursorStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    CursorRegisterExt();
}
#endif

#endif
